---
title: "ADD COURSE TITLE"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

# Intro {.sidebar}
ADD DASHBOARD DESCRIPTION

---

<center>
ADD COURSE LOGO
</center>

---
ADD COURSE INFO
Instructor: FILL   
Study load: FILL   
Assessment: FILL   


---

ADD COURSE SCHEDULE

|  When?  |      | Where? |
|:--------|:-----|:-------|
|  FILL   | 9 am | Online |
|  FILL   | 9 am | Online |
|  FILL   | 9 am | Online |
|  FILL   | 9 am | Online |
|  FILL   | 9 am | Online |
|  FILL   | 9 am | Online |

---



# Quick Overview

## Column 1

ADD A DESCRIPTION OF THE COURSE

### Assignment and Grading

ADD INFO ON GRADING


LINK TO OPEN IN COLAB


## Column 2

### Schedule
ADD SCHEDULE



# How to prepare

## Column 1

### Preparing your machine for the course

Add machine preparation

### System requirements

Add system requirements

## Column 2

### What if the steps to the left do not work for me?

Add info

# Monday
## Column 1

### Materials

Here you'll find the lecture slides as well as the practical for today.

- [Lecture](monday/Lectures/Lecture 1.pptx)

- [Practical 1 html](monday/Practicals/Practical 1.html) 
- [Practical 1 as notebook](https://colab.research.google.com/github/Goorbergh/applied_tm/blob/main/monday/Practicals/Practical%201.ipynb)  THIS MUST BE A PUBLIC REPOSITORY IN ORDER TO WORK!


## Column 2

### References

Add additional info/references

# Tuesday
## Column 1

### Materials

Add course material

[INSERT LINK NAME](INSERT FILE PATH)


## Column 2

### References

Add additional info/references

# Wednesday
## Column 1

### Materials

Add course material

[INSERT LINK NAME](INSERT FILE PATH)


## Column 2

### References

Add additional info/references

# Thursday
## Column 1

### Materials

Add course material

[INSERT LINK NAME](INSERT FILE PATH)


## Column 2

### References

Add additional info/references

# Friday
## Column 1

### Materials

Add course material

[INSERT LINK NAME](INSERT FILE PATH)


## Column 2

### References

Add additional info/references

